### ISSUE TITLE
codec mp4processor 

### ISSUE THREAD

**Issue by jhbnorika** [doggycoder/AudioVideo#5]
处理完黑屏视频是黑的－ －

**Comment by doggycoder** [comment]
处理完后sd卡下会生成temp.mp4，它是是黑的？

**Comment by jhbnorika** [comment]
你可以跑下那个apk，temp.mp4只有声音，没有视频

**Comment by jhbnorika** [comment]
能处理么，难道是surfacetexture，还是说渲染层问题？

**Comment by doggycoder** [comment]
https://github.com/doggycoder/AAVT ，可以跑下这个试试，我不太确定是手机的问题还是代码的问题，我这边看到的是正常的。

**Comment by jhbnorika** [comment]
aavt中com.wuwang.aavt.gl.BlurFilter 找不到这个类

**Comment by doggycoder** [comment]
换成GrayFilter

**Comment by jhbnorika** [comment]
Process: com.wuwang.aavt.examples, PID: 8170
                                                                        java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.wuwang.aavt.examples/com.wuwang.aavt.examples.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.wuwang.aavt.examples.MainActivity" on path: DexPathList[[zip file "/data/app/com.wuwang.aavt.examples-1/base.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.wuwang.aavt.examples-1/lib/arm, /vendor/lib, /system/lib]]
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "com.wuwang.aavt.examples.MainActivity" on path: DexPathList[[zip file "/data/app/com.wuwang.aavt.examples-1/base.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.wuwang.aavt.examples-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.wuwang.aavt.examples-1/lib/arm, /vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                            at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:148) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                        	Suppressed: java.lang.NoClassDefFoundError: com.wuwang.aavt.examples.MainActivity
                                                                            at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                            at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                            at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                            at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                            		... 13 more
                                                                        	Suppressed: java.lang.ClassNotFoundException: com.wuwang.aavt.examples.MainActivity
                                                                            at java.lang.Class.classForName(Native Method)
                                                                            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                        		at java.lang.BootC

**Comment by jhbnorika** [comment]
确实有，但是清空重编译，依然报上面的错误

**Comment by doggycoder** [comment]
好吧。不太清楚这个问题，没遇到过。你搜搜看。

**Comment by jhbnorika** [comment]
这个行，我换了个手机，原来那个版本有问题

**Comment by jhbnorika** [comment]
opengl部分有改么，这部分不熟

**Comment by jhbnorika** [comment]
比如之前的watermark那个水印位置怎么设置的，看了下像是opengl渲染上去的？

**Comment by jhbnorika** [comment]
缺个水印 － －

**Comment by jhbnorika** [comment]
处理完视频方向也不对

**Comment by doggycoder** [comment]
方向和水印都用OpenGL处理，可以查下相关资料。这个只是利用硬解硬编的示例。

**Comment by jhbnorika** [comment]
刚接触opengl，郁闷了0 0
